image: python:3

before_script:
  - pip install tox

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - tox -e flake8

isort:
  stage: lint
  script:
    - tox -e isort

# Wagtail 2.2
py34-dj20-wagtail22:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj20-wagtail22-factory-moto

py35-dj20-wagtail22:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj20-wagtail22-factory-moto

py36-dj20-wagtail22:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj20-wagtail22-factory-moto

py37-dj20-wagtail22:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj20-wagtail22-factory-moto

# Wagtail 2.1
py34-dj20-wagtail21:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj20-wagtail21-factory-moto

py35-dj20-wagtail21:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj20-wagtail21-factory-moto

py36-dj20-wagtail21:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj20-wagtail21-factory-moto

py37-dj20-wagtail21:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj20-wagtail21-factory-moto

# Wagtail 2.0
py34-dj20-wagtail20:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj20-wagtail20-factory-moto

py35-dj20-wagtail20:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj20-wagtail20-factory-moto

py36-dj20-wagtail20:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj20-wagtail20-factory-moto

py37-dj20-wagtail20:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj20-wagtail20-factory-moto
