language: python
cache: pip

matrix:
  include:
    - env: TOXENV=py37-dj22-wagtail27
      python: 3.7
    - env: TOXENV=py38-dj22-wagtail27
      python: 3.8
    - env: TOXENV=py38-dj30-wagtailmaster
      python: 3.8
    - env: TOXENV=flake8
      python: 3.8
    - env: TOXENV=isort
      python: 3.8
    - env: TOXENV=black
      python: 3.8
  allow_failures:
    - env: TOXENV=py38-dj30-wagtailmaster

install:
  - pip install tox codecov

script: tox

after_success:
  - codecov
